include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - sort_pub_dependencies
    - unnecessary_lambdas
    - use_super_parameters
