// Dispatches to the correct Firebase project based on --dart-define=FLAVOR=dev|prod.
// Do NOT edit this file — edit firebase_options_dev.dart or firebase_options_prod.dart.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'core/env/app_env.dart';
import 'firebase_options_dev.dart' as dev;
import 'firebase_options_prod.dart' as prod;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => AppEnv.isProd
      ? prod.DefaultFirebaseOptions.currentPlatform
      : dev.DefaultFirebaseOptions.currentPlatform;
}
