// Production Firebase project: dot-clash-72cc6
// Generated by FlutterFire CLI — regenerate with:
//   flutterfire configure --project=dot-clash-72cc6 --out=lib/firebase_options_prod.dart
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlgvfAzM_ym7e3bFtorYLGi8huxgzIsV0',
    appId: '1:727354434155:web:16c3925bc857b48a44072e',
    messagingSenderId: '727354434155',
    projectId: 'dot-clash-72cc6',
    authDomain: 'dot-clash-72cc6.firebaseapp.com',
    storageBucket: 'dot-clash-72cc6.firebasestorage.app',
    measurementId: 'G-LHD4K7J512',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB9GIrza-ogKm9U2YF1btPKBMVIQoQzvQ',
    appId: '1:727354434155:android:6abd475ba0f254f844072e',
    messagingSenderId: '727354434155',
    projectId: 'dot-clash-72cc6',
    storageBucket: 'dot-clash-72cc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVdfiTTSFHlO8F-BDpT_QV5UH2qcHtrK8',
    appId: '1:727354434155:ios:b130d397ad2b5aa144072e',
    messagingSenderId: '727354434155',
    projectId: 'dot-clash-72cc6',
    storageBucket: 'dot-clash-72cc6.firebasestorage.app',
    iosBundleId: 'com.vividmemories.dotclash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVdfiTTSFHlO8F-BDpT_QV5UH2qcHtrK8',
    appId: '1:727354434155:ios:1ae6dd120ecc0c5c44072e',
    messagingSenderId: '727354434155',
    projectId: 'dot-clash-72cc6',
    storageBucket: 'dot-clash-72cc6.firebasestorage.app',
    iosBundleId: 'testapoorv.dotClash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlgvfAzM_ym7e3bFtorYLGi8huxgzIsV0',
    appId: '1:727354434155:web:fbfc0432dc82d47144072e',
    messagingSenderId: '727354434155',
    projectId: 'dot-clash-72cc6',
    authDomain: 'dot-clash-72cc6.firebaseapp.com',
    storageBucket: 'dot-clash-72cc6.firebasestorage.app',
    measurementId: 'G-0FM9NG28LD',
  );
}
