#!/usr/bin/env bash
# Toggle native AdMob App IDs for prod closed-testing builds (iOS xcconfig override).
# Android uses --android-project-arg=betaAds=true at build time (see build_closed_testing.sh).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OVERRIDE="$ROOT/ios/Flutter/BetaAdsOverride.xcconfig"
ACTION="${1:-}"

case "$ACTION" in
  on)
    cat >"$OVERRIDE" <<'EOF'
// Generated by scripts/set_beta_ads_native.sh — do not commit.
GAD_APPLICATION_IDENTIFIER=ca-app-pub-3940256099942544~1458002511
EOF
    echo "Beta ads native override: ON ($OVERRIDE)"
    ;;
  off)
    rm -f "$OVERRIDE"
    echo "Beta ads native override: OFF"
    ;;
  *)
    echo "Usage: $0 on|off" >&2
    exit 1
    ;;
esac
